- .github/workflows/build.yaml
* Used directory for artifact for source path to avoid double compression
* The `.zip` file needed for the attestation step is still there.
* https://github.com/Screenly/Chrome-Extension/actions/runs/11819542064?pr=28
> fix: use directory instead of the `.zip` file for artifact path

- .github/workflows/build.yaml
* Fixes #27
* Creates a new step for publishing a release
* https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
* Please see this [CI run](https://github.com/nicomiguelino/devtools/actions/runs/11823148803) from [one of my personal repositories](https://github.com/nicomiguelino/devtools/blob/main/.github/workflows/build.yaml) for proof that the workflow works.
> chore(ci): add a workflow step for publishing a new release

- .github/workflows/build.yaml
- .gitignore
- README.md
- bin/package_extension.sh
- src/manifest.json
* Fixes #31 
* Bumps extension version (in manifest file) from `1.0.1` to `1.2.0`.
> fix: bump extension version to 1.2.0

- src/assets/js/boot-options.mjs
- src/assets/js/boot-popup.mjs
- src/assets/js/main.mjs
- src/assets/js/options.mjs
- src/assets/js/popup.mjs
- webpack.common.js
* Relative imports from JavaScript files can be cumbersome especially if you're importing multiple levels above the current directory.
> chore: use absolute imports

- src/assets/js/options.mjs
* The `user` objects contains the token that's stored in the browser session. It should be remove due to security purposes.
> chore: remove unsecure `console.info` statement

- package-lock.json
- package.json
* [`html-loader`](https://www.npmjs.com/package/html-loader), not to be confused with [`html-webpack-plugin`](https://www.npmjs.com/package/html-webpack-plugin), is not being used by the project.
* We only need to use `html-loader` if we are going to import HTML files in our JavaScript files.
> chore: remove `html-loader`

- src/assets/js/components/popup/proposal.jsx
> [!NOTE]
> No issues are associated with this pull request.
* The popup doesn't open on non-HTTP/S pagess
* Instead of closing the pop-up, the settings view is shown.
> fix: don't close the pop-up when opened on a non-HTTP/S page

- eslint.config.mjs
- src/assets/js/components/popup/popup-spinner.jsx
- src/assets/js/components/popup/proposal.jsx
- src/assets/js/components/popup/save-auth-help.jsx
- src/assets/js/components/popup/save-auth-warning.jsx
- src/assets/js/components/popup/settings.jsx
- src/assets/js/components/popup/sign-in-success.jsx
- src/assets/js/components/popup/sign-in.jsx
- src/assets/js/components/popup/success.jsx
- src/assets/js/components/popup/token-help-text.jsx
- src/assets/js/popup.jsx
- webpack.common.js
Fixes #77
Removes explicit imports of `React` for components
> chore: remove explicit imports of `React` for components

- .github/workflows/build.yaml
- bin/host_eslint.sh
- bin/package_extension.sh
- bin/run_tests.sh
- docker-compose.yml
* The **_Screenly/Browser-Extension_** project was once called **_Screenly/Chrome-Extension_**.
* We need to rename the Docker images for consistency.
> chore: rename Docker image name to `sbe_webpack`

- src/assets/ts/main.ts
* The function `getWebAsset` currently attempts to get an asset data by ID via a URL parameter.
* We should make use of a query parameter instead.
> fix: use query parameter to get asset data by id

- src/assets/ts/main.ts
For instance, when I add **_Asset A_**, then **_Asset B_** via the extension/add-on, opening the popup for Asset A shows **_Add to Screenly_** instead of **_Update Asset_**.
Looking closer at the issue, there's an issue with how states are saved to browser storage. Data is unexpectedly nested.
Logic for saving state in browser storage was updated to prevent unwanted nesting. For instance:
```
{
'state': {
'state': { ... }
}
}
```
Include any additional information that you think is necessary for this pull request,
including screenshots of the changes that you have made.
> fix: change state persistence logic to resolve unexpected data nesting

- src/assets/ts/components/proposal.tsx
The popup shows interface for updating a web asset even if that asset's already removed from Screenly via the web interface.
* If the asset was already deleted, the popup will show the interface for adding a new asset instead.
> fix: show screen for adding an asset if the asset was already removed

- src/assets/ts/components/proposal.tsx
- src/assets/ts/main.ts
In #101, if an asset was previously added via the browser extension and was then deleted via the Screenly web console, the key-value entry for that asset was never deleted&mdash;the values of most attributes are just set to `null`, `undefined`, `false`, or similar.
A new static method named `State.removeSavedAssetFromState(string)` was created to fully remove the key-value entry.
> fix: remove saved asset data from storage instead of nullifying it

- eslint.config.mjs
- src/assets/ts/main.ts
- src/assets/ts/popup.tsx
* Violating `no-unused-vars` would only raise a warning.
* ESLint will either raise nothing or only raise a warning when `no-undef` is violated.
* Updated ESLint config so that `no-unused-vars` and `no-undef` will be treated as errors.
> chore: raise ESLint errors for `no-unused-vars` and `no-undef`

- src/assets/ts/components/asset-save-failure.tsx
- src/assets/ts/components/asset-save-success.tsx
- src/assets/ts/components/check-mark.tsx
- src/assets/ts/components/proposal.tsx
- src/assets/ts/components/x-mark.tsx
- src/assets/ts/features/popup-slice.ts
- src/assets/ts/popup.tsx
* Fixes #104
* Creates new components for x-mark and asset save failure message.
> [!NOTE]
> As the failure situation is harder to replicate, I've temporarily tweaked poll rate and interval to have the failure message appear.
> fix: create new components for asset save failures; rename files

- README.md
- docker-compose.yml
Renames the `webpack` service to `browser-extension`.
> chore: rename `webpack` service to `browser-extension`

- src/assets/ts/main.ts
Replaced occurrences of raw query parameter strings with [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).
> chore: refactor URL params to use `URLSearchParams` instead

- src/assets/ts/features/asset/thunks/update-proposal.ts
I'm getting the following on some web pages:
I looked closely and found out that there was a PostgREST query error, giving a status code of 400.
Encodes source URL that will be looked up via the Screenly REST API
> fix: encode source URL during API lookup

- src/manifest-firefox.json
The following warnings show up during the upload of a new release:
- **Warning:** "strict_min_version" requires Firefox 60, which was released before 109 introduced support for "action".
- **Warning:** "strict_min_version" requires Firefox 60, which was released before 109 introduced support for "action.default_icon".
- **Warning:** "strict_min_version" requires Firefox 60, which was released before 109 introduced support for "action.default_popup".
- **Warning:** "strict_min_version" requires Firefox 60, which was released before 109 introduced support for "action.default_title".
- **Warning:** "strict_min_version" requires Firefox 60, which was released before 109 introduced support for "host_permissions".
- **Warning:** "strict_min_version" requires Firefox 60, which was released …
> fix: update minimum Firefox version in manifest file

- .github/workflows/build.yaml
- .github/workflows/test.yaml
- bin/package_extension.sh
- bin/run_eslint.sh
- bin/run_formatter.sh
- bin/run_tests.sh
- docker-compose.yml
- Renamed Docker image name from `sbe_webpack` to `screenly-browser-extension`
- In situations where a switch to another bundler (e.g. from WebPack to Vite, Rollup, Parcel, etc.) is needed, the current name `sbe_webpack` will not be relevant anymore.
> chore: rename Docker image name

- src/assets/ts/components/popup-page.tsx
- src/assets/ts/index.tsx
- webpack.common.js
- Moved the `PopupPage` component to a new file called `popup-page.tsx`
- Renamed the entrypoint file `popup.tsx` to `index.tsx`
> refactor: move `PopupPage` component to a new file
